# 総合演習問題 - 2

次のデータは，ある果物の糖度に対する試薬の効果を測定したものです．
各行はそれぞれの条件で育成した各グループごとの平均値です．

このデータを元にして，日照時間，平均気温，試薬量を説明変数として糖度を目的変数とする回帰直線の式を求めよ．

| 糖度 | 日照時間 | 平均気温 | 試薬量 |
| :---:|:---:| :---:| :---:|
| 19.0 | 199 | 28.1 | 1.44 |
| 17.9 | 206 | 18.0 | 1.32 |
| 19.6 | 196 | 24.8 | 1.24 |
| 16.1 | 163 | 19.7 | 1.47 |
| 12.7 | 146 | 24.9 | 1.39 |
| 14.4 | 158 | 18.4 | 1.43 |
| 16.0 | 140 | 21.2 | 1.49 |
| 21.9 | 210 | 26.0 | 1.47 |
| 13.8 | 165 | 25.8 | 1.22 |
| 19.0 | 217 | 17.5 | 1.35 |

ただし，糖度を（日照時間，平均温度，試薬量）より構成されるベクトル空間へ射影作用素を求めることを使って，Pythonで求めよ．  
回帰直線の式は，

> $[糖度] = 係数_1[日照時間] + 係数_2[平均温度] + 係数_3[試薬量] + 定数項$

です．

#### ヒント

定数項も考慮して，回帰式の係数となる変数を $x_1$：日照時間，$x_2$：平均温度，$x_3$：試薬量，$x_4$：定数項，として，
${\bf x} =
\left(\begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4 \\
\end{array}\right)$
とします．  
すると，これに対応する係数行列$\bf A$および，目的変数を$\bf b$として，行列方程式${\bf Ax}={\bf b}$を定義します．  
このとき，ベクトル$\bf b$を係数行列$\bf A$の列ベクトル空間へ射影したときの係数は，

> ${\bf x} = ({\bf A}^\mathsf{T}{\bf A})^{-1}{\bf A}^\mathsf{T}{\bf b}$

となります．

Pythonでデータ入力が必要になりますので，下記の記述をコピーしてご使用ください．

```Python
A = np.array([
    [ 199, 28.1, 1.44, 1 ],
    [ 206, 18.0, 1.32, 1 ],
    [ 196, 24.8, 1.24, 1 ],
    [ 163, 19.7, 1.47, 1 ],
    [ 146, 24.9, 1.39, 1 ],
    [ 158, 18.4, 1.43, 1 ],
    [ 140, 21.2, 1.49, 1 ],
    [ 210, 26.0, 1.47, 1 ],
    [ 165, 25.8, 1.22, 1 ],
    [ 217, 17.5, 1.35, 1 ]])

b = np.array([19.0,17.9,19.6,16.1,12.7,14.4,16.0,21.9,13.8,19.0])
```

*****
## 解答

まず最初にNumPyライブラリーをインポートします．

In [1]:
import numpy as np

方程式${\bf Ax}={\bf b}$の係数行列$\bf A$と定数ベクトル$\bf b$を定義します．

In [2]:
A = np.array([
    [ 199, 28.1, 1.44, 1 ],
    [ 206, 18.0, 1.32, 1 ],
    [ 196, 24.8, 1.24, 1 ],
    [ 163, 19.7, 1.47, 1 ],
    [ 146, 24.9, 1.39, 1 ],
    [ 158, 18.4, 1.43, 1 ],
    [ 140, 21.2, 1.49, 1 ],
    [ 210, 26.0, 1.47, 1 ],
    [ 165, 25.8, 1.22, 1 ],
    [ 217, 17.5, 1.35, 1 ]])
A

array([[ 199.  ,   28.1 ,    1.44,    1.  ],
       [ 206.  ,   18.  ,    1.32,    1.  ],
       [ 196.  ,   24.8 ,    1.24,    1.  ],
       [ 163.  ,   19.7 ,    1.47,    1.  ],
       [ 146.  ,   24.9 ,    1.39,    1.  ],
       [ 158.  ,   18.4 ,    1.43,    1.  ],
       [ 140.  ,   21.2 ,    1.49,    1.  ],
       [ 210.  ,   26.  ,    1.47,    1.  ],
       [ 165.  ,   25.8 ,    1.22,    1.  ],
       [ 217.  ,   17.5 ,    1.35,    1.  ]])

In [3]:
b = np.array([19.0,17.9,19.6,16.1,12.7,14.4,16.0,21.9,13.8,19.0])
b

array([ 19. ,  17.9,  19.6,  16.1,  12.7,  14.4,  16. ,  21.9,  13.8,  19. ])

係数行列のランクを調べます．
各列ベクトルが線形独立であれば，$\text{Rank}({\bf A})=4$ となります．

In [4]:
np.linalg.matrix_rank(A)

4

これにより，${\bf A}^\mathsf{T}{\bf A}$のランクも4となるので，この逆行列が存在します．
したがって，行列$\bf A$の列ベクトル空間への射影ベクトルの係数を求める作用素は，

> $({\bf A}^\mathsf{T}{\bf A})^{-1}{\bf A}^\mathsf{T}$

となります．Pythonでは，次の命令になります．

> numpy.linalg.inv(A.T.dot(A)).dot(A.T)

In [5]:
Solve = np.linalg.inv(A.T.dot(A)).dot(A.T)
Solve

array([[  3.49660195e-03,   3.02934025e-03,   8.83115989e-04,
         -1.60515223e-03,  -4.80404569e-03,  -2.78149469e-03,
         -4.70501701e-03,   5.36518700e-03,  -3.81160311e-03,
          4.93306754e-03],
       [  4.40615243e-02,  -3.42035097e-02,   1.31336590e-02,
         -1.77186863e-02,   1.76614648e-02,  -2.87222087e-02,
         -6.50651715e-03,   2.97889940e-02,   1.91780493e-02,
         -3.66727696e-02],
       [  1.12533796e+00,  -6.63070183e-01,  -1.56867028e+00,
          8.55941175e-01,  -1.75473024e-01,   2.49974509e-01,
          9.18247285e-01,   1.55590632e+00,  -2.11783376e+00,
         -1.80360004e-01],
       [ -3.07334602e+00,   1.23860851e+00,   1.81422214e+00,
         -3.96375981e-01,   8.10908673e-01,   8.99730635e-01,
         -1.76108440e-01,  -3.68446121e+00,   3.28257938e+00,
          2.84242317e-01]])

この作用素を目的変数であるベクトル$\bf b$に作用させれば，回帰式の係数$\bf x$が求まります．

In [6]:
x = Solve.dot(b)
x

array([  0.09440733,   0.12392496,  10.03166493, -16.59795628])

さらに，目的変数$\bf b$を行列$\bf A$の列ベクトル空間に射影した値は次のようになります．

In [7]:
A.dot(x)

array([ 20.11699108,  18.32240054,  17.41848375,  15.97830753,
        14.2152595 ,  14.94390184,  14.19345968,  21.19617925,
        14.41514819,  19.59986864])

以上で，線形代数の射影による回帰式が求まりました．
*****