# 総合演習問題 - 1

次の連立方程式の解を求めよ．

$$\left\{\begin{eqnarray}
 2x_1 +  x_2 + 2x_3 -  x_4  &=& 1 \\
 4x_1 + 2x_2 + 3x_3 -  x_4  &=& 1 \\
 6x_1 + 5x_2 + 3x_3 -  x_4  &=& 2 \\
-2x_1 - 3x_2 + 2x_3 - 2x_4  &=& 1 \\
\end{eqnarray} \right.$$

ヒント：Gaussの消去法によりPA=LU分解を行います．

*****
## 解答

連立方程式を行列の形式で表現します．

$${\bf A} =
\left(\begin{array}{c}
 2 &  1 & 2 & -1 \\
 4 &  2 & 3 & -1 \\
 6 &  5 & 3 & -1 \\
-2 & -3 & 2 & -2 \\
\end{array}\right)
, 
{\bf x} =
\left(\begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4 \\
\end{array}\right)
, 
{\bf b} =
\left(\begin{array}{c}
1 \\ 1 \\ 2 \\ 1 \\
\end{array}\right)$$

と置くと，問題は${\bf Ax}={\bf b}$と書けます．

解の求め方は，手計算で行いますが，同次にPythonによる計算も実施します．
そのためにNumPyライブラリーをインポートします．

```Python
import numpy as np
```

In [1]:
import numpy as np

拡大係数行列$\tilde{\bf A}$に対して，Gaussの消去法を適用していきます．

$$\tilde{\bf A} =
\left(\begin{array}{cccc:c}
 2 &  1 & 2 & -1 & 1 \\
 4 &  2 & 3 & -1 & 1 \\
 6 &  5 & 3 & -1 & 2 \\
-2 & -3 & 2 & -2 & 1 \\
\end{array}\right)$$

拡大拡張係数行列をPythonでは，AAという変数名に代入します．

```Python
AA = np.array([[ 2, 1, 2,-1, 1],
               [ 4, 2, 3,-1, 1],
               [ 6, 5, 3,-1, 2],
               [-2,-3, 2,-2, 1]])
AA
```

In [2]:
AA = np.array([[ 2, 1, 2,-1, 1],
               [ 4, 2, 3,-1, 1],
               [ 6, 5, 3,-1, 2],
               [-2,-3, 2,-2, 1]])
AA

array([[ 2,  1,  2, -1,  1],
       [ 4,  2,  3, -1,  1],
       [ 6,  5,  3, -1,  2],
       [-2, -3,  2, -2,  1]])

最初の前進消去です．
1列目の2行目以下の値をゼロにするための変換行列として${\bf R}_1$を次のように定義します．

$${\bf R}_1 =
\left(\begin{array}{c}
 1 & 0 & 0 & 0 \\
-2 & 1 & 0 & 0 \\
-3 & 0 & 1 & 0 \\
 1 & 0 & 0 & 1 \\
\end{array}\right)$$

```Python
R1 = np.array([[ 1,0,0,0],
               [-2,1,0,0],
               [-3,0,1,0],
               [ 1,0,0,1]])
R1
```

In [3]:
R1 = np.array([[ 1,0,0,0],
               [-2,1,0,0],
               [-3,0,1,0],
               [ 1,0,0,1]])
R1

array([[ 1,  0,  0,  0],
       [-2,  1,  0,  0],
       [-3,  0,  1,  0],
       [ 1,  0,  0,  1]])

拡大係数行列の左から${\bf R}_1$を作用させます．

$${\bf R}_1\tilde{\bf A} =
\left(\begin{array}{c}
 1 & 0 & 0 & 0 \\
-2 & 1 & 0 & 0 \\
-3 & 0 & 1 & 0 \\
 1 & 0 & 0 & 1 \\
\end{array}\right)
\left(\begin{array}{cccc:c}
 2 &  1 & 2 & -1 & 1 \\
 4 &  2 & 3 & -1 & 1 \\
 6 &  5 & 3 & -1 & 2 \\
-2 & -3 & 2 & -2 & 1 \\
\end{array}\right)
=
\left(\begin{array}{cccc:c}
2 &  1 &  2 & -1 &  1 \\
0 &  0 & -1 &  1 & -1 \\
0 &  2 & -3 &  2 & -1 \\
0 & -2 &  4 & -3 &  2 \\
\end{array}\right) $$

行列の掛け算をPythonでは dot()メソッドで実現します．

```Python
R1.dot(AA)
```

In [4]:
R1.dot(AA)

array([[ 2,  1,  2, -1,  1],
       [ 0,  0, -1,  1, -1],
       [ 0,  2, -3,  2, -1],
       [ 0, -2,  4, -3,  2]])

この結果として，2行2列目の値がゼロになってしまいました．
そこで，2行目と3行目を入替えることにします．
この入替えは

$${\bf P} =
\left(\begin{array}{c}
1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
\end{array}\right) $$

を左から掛けることによって実現します．

行列Pを定義します．

```Python
P = np.array([[1,0,0,0],
              [0,0,1,0],
              [0,1,0,0],
              [0,0,0,1]])
P
```

In [5]:
P = np.array([[1,0,0,0],
              [0,0,1,0],
              [0,1,0,0],
              [0,0,0,1]])
P

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

行列の積${\bf P}{\bf R}_1\tilde{\bf A}$を計算します．

```Python
P.dot(R1.dot(AA))
```

In [6]:
P.dot(R1.dot(AA))

array([[ 2,  1,  2, -1,  1],
       [ 0,  2, -3,  2, -1],
       [ 0,  0, -1,  1, -1],
       [ 0, -2,  4, -3,  2]])

例によって，連立方程式の並び順を最初から都合の良い順番にするため，行の入替え行列を拡大係数行列に最初に作用するように変更します．

$${\bf P}{\bf R}_1\tilde{\bf A} = ({\bf P}{\bf R}_1{\bf P}){\bf P}\tilde{\bf A}$$

この式における$({\bf P}{\bf R}_1{\bf P})$は，計算せずとも2行1列と3行1列の成分を入替えれば求まります．

$${\bf P}{\bf R}_1{\bf P} 
=
\left(\begin{array}{c}
1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
\end{array}\right)
\left(\begin{array}{c}
 1 & 0 & 0 & 0 \\
-2 & 1 & 0 & 0 \\
-3 & 0 & 1 & 0 \\
 1 & 0 & 0 & 1 \\
\end{array}\right)
\left(\begin{array}{c}
1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
\end{array}\right)
=
\left(\begin{array}{c}
 1 & 0 & 0 & 0 \\
-3 & 1 & 0 & 0 \\
-2 & 0 & 1 & 0 \\
 1 & 0 & 0 & 1 \\
\end{array}\right) $$

この行列を$\tilde{\bf R}_1$と書くことにします．
プログラム上での変数名はRR1とします．

```Python
RR1 = P.dot(R1.dot(P))
RR1
```

In [7]:
RR1 = P.dot(R1.dot(P))
RR1

array([[ 1,  0,  0,  0],
       [-3,  1,  0,  0],
       [-2,  0,  1,  0],
       [ 1,  0,  0,  1]])

行列の積$\tilde{\bf R}_1{\bf P}\tilde{\bf A}$を計算します．

```Python
RR1.dot(P.dot(AA))
```

In [8]:
RR1.dot(P.dot(AA))

array([[ 2,  1,  2, -1,  1],
       [ 0,  2, -3,  2, -1],
       [ 0,  0, -1,  1, -1],
       [ 0, -2,  4, -3,  2]])

前進消去を進めます．

$$\tilde{\bf R}_1{\bf P}\tilde{\bf A} =
\left(\begin{array}{cccc:c}
2 &  1 &  2 & -1 &  1 \\
0 &  2 & -3 &  2 & -1 \\
0 &  0 & -1 &  1 & -1 \\
0 & -2 &  4 & -3 &  2 \\
\end{array}\right) $$

ここから，4行2列目の値をゼロにする行列${\bf R}_2$を定義します．

$${\bf R}_2 =
\left(\begin{array}{c}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 \\
\end{array}\right)$$

```Python
R2 = np.array([[1,0,0,0],
               [0,1,0,0],
               [0,0,1,0],
               [0,1,0,1]])
R2
```

In [9]:
R2 = np.array([[1,0,0,0],
               [0,1,0,0],
               [0,0,1,0],
               [0,1,0,1]])
R2

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1]])

$${\bf R}_2 \tilde{\bf R}_1{\bf P}\tilde{\bf A} 
=
\left(\begin{array}{c}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 \\
\end{array}\right)
\left(\begin{array}{cccc:c}
2 &  1 &  2 & -1 &  1 \\
0 &  2 & -3 &  2 & -1 \\
0 &  0 & -1 &  1 & -1 \\
0 & -2 &  4 & -3 &  2 \\
\end{array}\right) 
=
\left(\begin{array}{cccc:c}
2 & 1 &  2 & -1 &  1 \\
0 & 2 & -3 &  2 & -1 \\
0 & 0 & -1 &  1 & -1 \\
0 & 0 &  1 & -1 &  1 \\
\end{array}\right) $$

${\bf R}_2$を$\tilde{\bf R}_1{\bf P}\tilde{\bf A}$に掛けます．

```Python
R2.dot(RR1.dot(P.dot(AA)))
```

In [10]:
R2.dot(RR1.dot(P.dot(AA)))

array([[ 2,  1,  2, -1,  1],
       [ 0,  2, -3,  2, -1],
       [ 0,  0, -1,  1, -1],
       [ 0,  0,  1, -1,  1]])

次に，4行3列目の値をゼロにする行列${\bf R}_3$を定義します．

$${\bf R}_3 =
\left(\begin{array}{c}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 1 & 1 \\
\end{array}\right)$$

```Python
R3 = np.array([[1,0,0,0],
               [0,1,0,0],
               [0,0,1,0],
               [0,0,1,1]])
R3
```

In [11]:
R3 = np.array([[1,0,0,0],
               [0,1,0,0],
               [0,0,1,0],
               [0,0,1,1]])
R3

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 1]])

$${\bf R}_3 {\bf R}_2 \tilde{\bf R}_1{\bf P}\tilde{\bf A} 
=
\left(\begin{array}{c}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 1 & 1 \\
\end{array}\right)
\left(\begin{array}{cccc:c}
2 &  1 &  2 & -1 &  1 \\
0 &  2 & -3 &  2 & -1 \\
0 &  0 & -1 &  1 & -1 \\
0 & 0 &  1 & -1 &  1 \\
\end{array}\right) 
=
\left(\begin{array}{cccc:c}
2 & 1 &  2 & -1 &  1 \\
0 & 2 & -3 &  2 & -1 \\
0 & 0 & -1 &  1 & -1 \\
0 & 0 &  0 &  0 &  0 \\
\end{array}\right) $$

この結果，4行4列目もゼロになってしまったので，前進消去はここで終了です．

```Python
R3.dot(R2.dot(RR1.dot(P.dot(AA))))
```

In [12]:
R3.dot(R2.dot(RR1.dot(P.dot(AA))))

array([[ 2,  1,  2, -1,  1],
       [ 0,  2, -3,  2, -1],
       [ 0,  0, -1,  1, -1],
       [ 0,  0,  0,  0,  0]])

なお，この計算では括弧が多くなりプログラムが見にくくなります．
そこで，行列の積の結合法則を用いて次のように書き換えることができます．

```Python
R3.dot(R2).dot(RR1).dot(P).dot(AA)
```

In [13]:
R3.dot(R2).dot(RR1).dot(P).dot(AA)

array([[ 2,  1,  2, -1,  1],
       [ 0,  2, -3,  2, -1],
       [ 0,  0, -1,  1, -1],
       [ 0,  0,  0,  0,  0]])

この結果から5列目を除いた行列が係数行列に対応する階段行列$\bf U$です．

```Python
U = R3.dot(R2.dot(RR1.dot(P.dot(AA))))[:,:4]
U
```

In [14]:
U = R3.dot(R2.dot(RR1.dot(P.dot(AA))))[:,:4]
U

array([[ 2,  1,  2, -1],
       [ 0,  2, -3,  2],
       [ 0,  0, -1,  1],
       [ 0,  0,  0,  0]])

LU分解における行列$\bf L$は，

$${\bf L} = {\tilde{\bf R}_1}^{-1} {{\bf R}_2}^{-1} {\tilde{\bf R}_3}^{-1}
=
\left(\begin{array}{c}
 1 &  0 &  0 & 0 \\
 3 &  1 &  0 & 0 \\
 2 &  0 &  1 & 0 \\
-1 & -1 & -1 & 1 \\
\end{array}\right)$$

となります．

```Python
L = np.linalg.inv(RR1).dot(np.linalg.inv(R2)).dot(np.linalg.inv(R3))
L
```

In [15]:
L = np.linalg.inv(RR1).dot(np.linalg.inv(R2)).dot(np.linalg.inv(R3))
L

array([[ 1.,  0.,  0.,  0.],
       [ 3.,  1.,  0.,  0.],
       [ 2.,  0.,  1.,  0.],
       [-1., -1., -1.,  1.]])

確かに${\bf LU}={\bf PA}$となっていることがPythonによる計算で確認できます．

```Python
L.dot(U)
```

In [16]:
L.dot(U)

array([[ 2.,  1.,  2., -1.],
       [ 6.,  5.,  3., -1.],
       [ 4.,  2.,  3., -1.],
       [-2., -3.,  2., -2.]])

最終的な階段行列と変数との関係を確認します．

$$\left(\begin{array}{cccc:c}
x_1 & x_2 & x_3 & x_4 \\ \hline
2 & 1 &  2 & -1 &  1 \\
0 & 2 & -3 &  2 & -1 \\
0 & 0 & -1 &  1 & -1 \\
0 & 0 &  0 &  0 &  0 \\
\end{array}\right) $$

この結果，変数$x_4$にはピボットが無いので自由変数となります．

この後は，後退代入によって，変数の値を求めていきます．
最後に求まった行列を方程式の形に戻します．

$$\left\{\begin{eqnarray}
2x_1 +  x_2 + 2x_3 -  x_4 &=&  1 & \cdots (1) \\
       2x_2 - 3x_3 + 2x_4 &=& -1 & \cdots (2) \\
            -  x_3 +  x_4 &=& -1 & \cdots (3) \\
\end{eqnarray} \right.$$

$x_4$は自由変数なので，

$$x_4=t$$

と置きます．
式(3)より，

$$x_3 = x_4 + 1 = t+1$$

が求まります．
次に式(2)より，

$$x_2 = \frac{1}{2}(3x_3-2x_4-1) = \frac{1}{2} \{3{\cdot}(t+1) - 2t -1 \} = \frac{1}{2}t+1$$

が求まります．
最後に式(1)より，

$$x_1 = \frac{1}{2} \{ -x_2-2x_3+x_4+1 \} = \frac{1}{2} \{ -(\frac{1}{2}t+1)-2(t+1)+t+1 \} = -\frac{3}{4}t-1$$

となります．
これをまとめると，ベクトル$\bf x$が求まります．

> ${\bf x} =
\left(\begin{array}{c}
-\frac{3}{4}t-1 \\
\frac{1}{2}t+1 \\
t+1 \\
t \\
\end{array}\right)$
$=
\left(\begin{array}{c}
-3 \\
2 \\
4 \\
4 \\
\end{array}\right) \frac{t}{4}
+
\left(\begin{array}{c}
-1 \\
1 \\
1 \\
0 \\
\end{array}\right) $

これが，問題の連立方程式の一般解です．

これで課題の解答は完了しました．
参考として別の解法も紹介します．

*****
## SciPyライブラリーによる解

参考までに，SciPyライブラリーのlinalg.lu_factor()関数による解を見て見ましょう．

まずはSciPyライブラリーをインポートします．

```Python
import scipy.linalg as linalg
```

In [17]:
import scipy.linalg as linalg

linalg.lu_factor()関数によってLU分解を実施します．

```Python
LU = linalg.lu_factor(AA[:,:4])
LU
```

In [18]:
LU = linalg.lu_factor(AA[:,:4])
LU

(array([[  6.00000000e+00,   5.00000000e+00,   3.00000000e+00,
          -1.00000000e+00],
        [ -3.33333333e-01,  -1.33333333e+00,   3.00000000e+00,
          -2.33333333e+00],
        [  6.66666667e-01,   1.00000000e+00,  -2.00000000e+00,
           2.00000000e+00],
        [  3.33333333e-01,   5.00000000e-01,   2.50000000e-01,
           5.55111512e-17]]), array([2, 3, 3, 3], dtype=int32))

定数項を与えて，連立方程式の解を求めます．

```Python
linalg.lu_solve(LU,np.array([1,1,2,1]))
```

In [19]:
linalg.lu_solve(LU,np.array([1,1,2,1]))

array([-0.25,  0.5 ,  0.  , -1.  ])

このベクトル
$\left(\begin{array}{c}
-0.25 \\ 0.5 \\ 0 \\ -1 \\  
\end{array}\right)$
は，上で求めた一般解において$t=-1$と置いた値になっています．

このlinalg.lu_factor()関数を使えば簡単に答えが出ますが，
解が無限にある場合の解空間の構造を明確にしてくれるわけではありません．
ツールを使うだけの人にならないようにしましょう．

*****