# 演習問題

次の行列のLU分解を求めよ．

${\bf A} =
\left(\begin{array}{c}
1 & 2 & -1 \\
2 & 6 & -2 \\
3 & 4 &  1 \\
\end{array}\right)$

最初に手計算で求めてください．

次に，その結果が正しいことをPythonで検証してください．

*****
## 解答

方針は，Gaussの消去法のおける前進消去を行います．
そのために，行列$\bf A$にピボット以外をゼロにするような基本行列を次々と掛けていきます．

最初は1列目の前進消去です．
2行3列目と3行2列目の値をゼロにするような行列${\bf T}_1$を考えます．

${\bf T}_1 = {\bf R}_3(3,1;-3){\bf R}_3(2,1;-2)
\left(\begin{array}{c}
 1 & 0 & \\
 0 & 1 & 0 \\
-3 & 0 & 1 \\
\end{array}\right)
\left(\begin{array}{c}
 1 & 0 & \\
-2 & 1 & 0 \\
 0 & 0 & 1 \\
\end{array}\right)
=
\left(\begin{array}{c}
 1 & 0 & \\
-2 & 1 & 0 \\
-3 & 0 & 1 \\
\end{array}\right) $

この行列を$\bf A$に掛けると次のようになります．

${\bf T}_1{\bf A} =
\left(\begin{array}{c}
 1 & 0 & 0 \\
-2 & 1 & 0 \\
-3 & 0 & 1 \\
\end{array}\right)
\left(\begin{array}{c}
1 & 2 & -1 \\
2 & 6 & -2 \\
3 & 4 &  1 \\
\end{array}\right)
=
\left(\begin{array}{c}
1 &  2 & -1 \\
0 &  2 &  0 \\
0 & -2 &  4 \\
\end{array}\right) $

次に2列目の前進消去を行います．
3行2列目の値をゼロにする行列は，${\bf T}_2={\bf R}_3(3,2;1)$です．
これを${\bf T}_1{\bf A}$に掛けます．

${\bf T}_2{\bf T}_1{\bf A} =
\left(\begin{array}{c}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 1 & 1 \\
\end{array}\right)
\left(\begin{array}{c}
1 & 2 & -1 \\
0 & 6 &  0 \\
0 & 4 &  4 \\
\end{array}\right)
=
\left(\begin{array}{c}
1 & 2 & -1 \\
0 & 2 &  0 \\
0 & 0 &  4 \\
\end{array}\right) $

この結果は，上三角行列になりましたので，この行列を$\bf U$とします．

次に下三角行列を求めます．

$\begin{eqnarray}
{\bf L} &=& ({\bf R}_3(3,2;1){\bf R}_3(3,1;-3){\bf R}_3(2,1;-2))^{-1}  \\
&=& ({\bf R}_3(2,1;-2))^{-1}({\bf R}_3(3,1;-3))^{-1}({\bf R}_3(3,2;1))^{-1} \\
&=& ({\bf R}_3(2,1;2){\bf R}_3(3,1;3){\bf R}_3(3,2;-1) \\
&=& 
\left(\begin{array}{c}
1 &  0 & 0 \\
2 &  1 & 0 \\
3 & -1 & 1 \\
\end{array}\right)
\end{eqnarray}$

次にPythonで，この結果を検証します．

まずはPythonの配列計算ライブラリーであるNumPyをインポートします．

In [1]:
import numpy as np

In [2]:
A =np.array([[1,2,-1],
             [2,6,-2],
             [3,4, 1]])
A

array([[ 1,  2, -1],
       [ 2,  6, -2],
       [ 3,  4,  1]])

In [3]:
T1 = np.array([[ 1,0,0],
               [-2,1,0],
               [-3,0,1]])
T1.dot(A)

array([[ 1,  2, -1],
       [ 0,  2,  0],
       [ 0, -2,  4]])

In [4]:
T2 = np.array([[1,0,0],
               [0,1,0],
               [0,1,1]])
U = T2.dot(T1).dot(A)
U

array([[ 1,  2, -1],
       [ 0,  2,  0],
       [ 0,  0,  4]])

よって，上三角行列が確認できました．

下三角行列は，${\bf L}=({\bf T}_2{\bf T}_1)^{-1}$によって確認します．

In [5]:
np.linalg.inv(T2.dot(T1))

array([[ 1.,  0.,  0.],
       [ 2.,  1.,  0.],
       [ 3., -1.,  1.]])

結果として，下三角行列についても確認できました．
*****