# 多変数の最小二乗近似問題

変数が複数ある解の無い連立方程式の近似解を求める問題を解いていきます．



変数の個数を$n$個，一次方程式の個数を$m$個である連立一次方程式を

$ {\bf A} =
\left(\begin{array}{c}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} \\
\end{array}\right)$ 
, 
$ {\bf x} =
\left(\begin{array}{c}
x_1 \\ x_2 \\ \vdots \\ x_n \\
\end{array}\right)$ 
,
$ {\bf b} =
\left(\begin{array}{c}
b_1 \\ b_2 \\ \vdots \\ b_m \\
\end{array}\right)$

として，行列の形式で${\bf Ax}={\bf b}$と表します．

最小二乗法では$\| {\bf Ax}-{\bf b} \|$を最小にする$\bf x$が近似解です．  
このときベクトル${\bf p}={\bf Ax}$は，行列$\bf A$の列ベクトルによって構成される部分空間へのベクトル$\bf b$の射影ベクトルに一致します．

> ${\bf p} = {\bf A}({\bf A}^\mathsf{T}{\bf A})^{-1}{\bf A}^\mathsf{T}{\bf b}$

すなわち，近似解$\bf x$は次のようになります．

> ${\bf x} = ({\bf A}^\mathsf{T}{\bf A})^{-1}{\bf A}^\mathsf{T}{\bf b}$

*****
## 最小二乗法が射影になることの確認

煩雑さを避けるために2変数で3個の方程式からなる連立方程式の場合について説明します．
すなわち，次の連立方程式を扱います．

$$
\left\{ \begin{array}{c}
a_{11}x_1+a_{12}x_2 = b_1 \\
a_{21}x_1+a_{22}x_2 = b_2 \\
a_{31}x_1+a_{32}x_2 = b_3 \\ 
\end{array}\right.
$$



この連立方程式から係数行列とベクトルを
${\bf A} =
\left( \begin{array}{c}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
a_{31} & a_{32} \\
\end{array}\right) $
,
$ {\bf x} =
\left(\begin{array}{c}
x_1 \\ x_2 \\
\end{array}\right) $
,
$ {\bf b} =
\left(\begin{array}{c}
b_1 \\ b_2 \\ b_3 \\
\end{array}\right) $
と定義します．

最小二乗法では，$y = {\|{\bf Ax}-{\bf b}\|}^2$が最小となる$\bf x$を求めます．  
その解は，曲面とその微分係数との関係から，各変数による偏微分がゼロとなります．
すなわち，

$$ 
\left(\begin{array}{c}
\frac{\partial y}{\partial x_1} \\ \frac{\partial y}{\partial x_2}
\end{array}\right)
= 0
$$

が成立します．この微分を実際に計算していきます．

$$
y = (a_{11}x_1+a_{12}x_2-b_1)^2 + (a_{21}x_1+a_{22}x_2-b_2)^2 + (a_{31}x_1+a_{32}x_2-b_3)^2
$$

となるので，この式を各変数で微分すると，

$$
\frac{\partial y}{\partial x_1} = 2a_{11}(a_{11}x_1+a_{12}x_2-b_1)+2a_{21}(a_{21}x_1+a_{22}x_2-b_2)+2a_{31}(a_{31}x_1+a_{32}x_2-b_3)
$$
$$
\frac{\partial y}{\partial x_2} = 2a_{12}(a_{11}x_1+a_{12}x_2-b_1)+2a_{22}(a_{21}x_1+a_{22}x_2-b_2)+2a_{32}(a_{31}x_1+a_{32}x_2-b_3)
$$


これらの計算式を
$\left(\begin{array}{c}
\frac{\partial y}{\partial x_1} \\ \frac{\partial y}{\partial x_2}
\end{array}\right)
= 0$
に代入して整理すると，次の行列式が得られます．

$$
\left(\begin{array}{c}
(a_{11}a_{11}+a_{21}a_{21}+a_{31}a_{31})x_1 + (a_{11}a_{12}+a_{21}a_{22}+a_{31}a_{32})x_2 \\
(a_{12}a_{11}+a_{22}a_{21}+a_{32}a_{31})x_1 + (a_{12}a_{12}+a_{22}a_{22}+a_{33}a_{32})x_2 \\
\end{array}\right)
=
\left(\begin{array}{c}
a_{11}b_1+a_{21}b_2+a_{31}b_3 \\
a_{12}b_1+a_{22}b_2+a_{32}b_3 \\
\end{array}\right)
$$

ここで，変数ベクトル
$ {\bf x} =
\left(\begin{array}{c}
x_1 \\ x_2 \\
\end{array}\right) $
と定数ベクトル
$ {\bf b} =
\left(\begin{array}{c}
b_1 \\ b_2 \\ b_3 \\
\end{array}\right) $
を積の形式に分離することができます．

$$
\left(\begin{array}{c}
a_{11}a_{11}+a_{21}a_{21}+a_{31}a_{31} & a_{11}a_{12}+a_{21}a_{22}+a_{31}a_{32} \\
a_{12}a_{11}+a_{22}a_{21}+a_{32}a_{31} & a_{12}a_{12}+a_{22}a_{22}+a_{33}a_{32} \\
\end{array}\right)
\left(\begin{array}{c}
x_1 \\ x_2 \\
\end{array}\right)
=
\left(\begin{array}{c}
a_{11} & a_{21} & a_{31} \\
a_{12} & a_{22} & a_{32} \\
\end{array}\right)
\left(\begin{array}{c}
b_1 \\ b_2 \\ b_3 \\
\end{array}\right)
$$

ここで行列$\bf A$の定義から，右辺の係数行列が${\bf A}^{\mathsf T}$になっていることが直ちに分かります．  
また，この式の左辺の係数行列が${\bf A}^{\mathsf T}{\bf A}$であることが分かります．
実際に計算すると，

$$
{\bf A}^{\mathsf T}{\bf A} 
=
\left(\begin{array}{c}
a_{11} & a_{21} & a_{31} \\
a_{12} & a_{22} & a_{32} \\
\end{array}\right)
\left( \begin{array}{c}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
a_{31} & a_{32} \\
\end{array}\right)
=
\left(\begin{array}{c}
a_{11}a_{11}+a_{21}a_{21}+a_{31}a_{31} & a_{11}a_{12}+a_{21}a_{22}+a_{31}a_{32} \\
a_{12}a_{11}+a_{22}a_{21}+a_{32}a_{31} & a_{12}a_{12}+a_{22}a_{22}+a_{33}a_{32} \\
\end{array}\right)
$$

となります．
従って，

$$ {\bf A}^{\mathsf T}{\bf A}{\bf x} = {\bf A}^{\mathsf T}{\bf b} $$

が得られます．
${\bf A}^{\mathsf T}{\bf A}$の逆行列を両辺に掛ければ射影の式になります．

$$ {\bf x} = ({\bf A}^{\mathsf T}{\bf A})^{-1}{\bf A}^{\mathsf T}{\bf b} $$

以上で，最小二乗法による近似解が射影ベクトルになることが示されました．

*****
## Pythonによる例題の解法

次に3変数の5つの一次方程式からなる連立方程式の問題に対応します．

$$
\left\{ \begin{array}{c}
 x_1 - 3x_2 + 2x_3 = 1 \\
2x_1 + 3x_2 - 2x_3 = 3 \\
 x_1 - 2x_2 + 2x_3 = 5 \\
     -  x_2 + 2x_3 = 7 \\
 x_1 -  x_2 + 2x_3 = 9 \\
\end{array} \right. 
$$

この連立方程式を行列で${\bf Ax}={\bf b}$の形で表現すると次のようになります．

$$
\left(\begin{array}{c}
1 & -3 &  2  \\
2 &  3 & -2  \\
1 & -2 &  2  \\
0 & -1 &  2  \\
1 & -1 &  2  \\
\end{array}\right)
\left(\begin{array}{c}
x_1 \\ x_2 \\ x_3  \\
\end{array}\right)
=
\left(\begin{array}{c}
1 \\ 3 \\ 5 \\ 7 \\ 9 \\
\end{array}\right) 
$$

この行列方程式をPythonで解いていくためにNumPyライブラリーをインポートします．

In [1]:
import numpy as np

係数行列を配列オブジェクトとして定義して，変数名をAとします．

In [2]:
A = np.array([[1,-3,2],
              [2,3,-2],
              [1,-2,2],
              [0,-1,2],
              [1,-1,2]])

定数ベクトルも配列オブジェクトとして定義して，変数名をbとします．

In [3]:
b = np.array([1,3,5,7,9])

この係数行列のランクを調べます．

In [4]:
np.linalg.matrix_rank(A)

3

係数行列$\bf A$の列ベクトル空間へのベクトル$\bf b$の射影を求める過程でベクトル$\bf x$は次の行列計算で求めることができます．

> ${\bf x} = ({\bf A}^\mathsf{T}{\bf A})^{-1}{\bf A}^\mathsf{T}{\bf b}$

この計算は一つの式で実施できますが，ここでは細かく分解して，それぞれの計算を可視化します．

$\bf A$の転置行列${\bf A}^\mathsf{T}$を求めます．
numpy.array配列の転置行列は，オブジェクトのT属性で求めることができます．

> A.T

In [5]:
A.T

array([[ 1,  2,  1,  0,  1],
       [-3,  3, -2, -1, -1],
       [ 2, -2,  2,  2,  2]])

対称行列${\bf A}^\mathsf{T}{\bf A}$を求めます．
numpyではドット積によって求められます．

> A.T.dot(A)

In [6]:
A.T.dot(A)

array([[  7,   0,   2],
       [  0,  24, -20],
       [  2, -20,  20]])

行列${\bf A}^\mathsf{T}{\bf A}$のランクは$\bf A$のランクに等しいので，この行列は正則な行列になっています．  
さらにその逆行列$({\bf A}^\mathsf{T}{\bf A})^{-1}$について，numpy.linalg.inv()関数で求めます．

>np.linalg.inv(A.T.dot(A))

In [7]:
np.linalg.inv(A.T.dot(A))

array([[ 0.17241379, -0.0862069 , -0.10344828],
       [-0.0862069 ,  0.29310345,  0.30172414],
       [-0.10344828,  0.30172414,  0.36206897]])

行列方程式${\bf Ax}={\bf b}$の最小近似解$\bf x$を求めるための行列は，${\bf Solve}=({\bf A}^\mathsf{T}{\bf A})^{-1}{\bf A}^\mathsf{T}$でした．
これをnumpyの関数やドット積を組み合わせることによって求めます．

> Solve = np.linalg.inv(A.T.dot(A)).dot(A.T)

In [8]:
Solve = np.linalg.inv(A.T.dot(A)).dot(A.T)
Solve

array([[ 0.22413793,  0.29310345,  0.13793103, -0.12068966,  0.05172414],
       [-0.36206897,  0.10344828, -0.06896552,  0.31034483,  0.22413793],
       [-0.28448276, -0.02586207,  0.01724138,  0.42241379,  0.31896552]])

この行列を定数ベクトル$\bf b$に作用させると，行列方程式${\bf Ax}={\bf b}$の最小近似解が求まります．

> x = Solve.dot(b)

In [9]:
x = Solve.dot(b)
x

array([ 1.4137931 ,  3.79310345,  5.55172414])

この近似解に行列$\bf A$を作用されると，ベクトル$\bf b$の行列$\bf A$の列ベクトル空間への射影が求まります．

In [10]:
A.dot(x)

array([ 1.13793103,  3.10344828,  4.93103448,  7.31034483,  8.72413793])

この射影ベクトルは，定数ベクトル
${\bf b}=
\left(\begin{array}{c}
1 \\ 3 \\ 5 \\ 7 \\ 9 \\
\end{array}\right)$
に近い値になっていることが分かります．

また，射影行列は次のようになります．

In [12]:
P = A.dot(Solve)
P

array([[ 0.74137931, -0.06896552,  0.37931034, -0.20689655,  0.01724138],
       [-0.06896552,  0.94827586,  0.03448276, -0.15517241,  0.13793103],
       [ 0.37931034,  0.03448276,  0.31034483,  0.10344828,  0.24137931],
       [-0.20689655, -0.15517241,  0.10344828,  0.53448276,  0.4137931 ],
       [ 0.01724138,  0.13793103,  0.24137931,  0.4137931 ,  0.46551724]])

*****
このように，多変数の連立方程式で解が存在しない場合に最小二乗法による近似解を求めることを，行列の列空間への射影ベクトルを計算する方法により実現することができました．